### ISSUE TITLE
Buttons no longer working

### ISSUE THREAD

**Issue by notenoughtech** [stephenkeep/node-red-contrib-amazondash#14]
Both generation buttons are no longer working - I can see buttons registering on the network, but node red is not picking it up, also nodes give  a deployment error:
`Error: Error: No devices to listen`

**Comment by alexhoffenreich** [comment]
Hi,
Im just starting with this and having the same issue
Did you manage to fix it?

**Comment by notenoughtech** [comment]
I reinstalled the node, and updated npm - it is working now. Reboot pi as well
