### ISSUE TITLE
Error: Error: No devices to listen

### ISSUE THREAD

**Issue by nilsbernhar** [stephenkeep/node-red-contrib-amazondash#9]
Hello,
i finally got the node to install. Nonetheless, I now get an error when having the node in a flow and deploying. Once deployed, the node immediately sends the error:
`Error: Error: No devices to listen`
even though I did add the right MAC Adress (copied out of the findbutton-skript and double checked with my router settings-page).
What I noticed is, that I do get four
`node_pcap: EthernetFrame() - Don't know how to decode ethertype 34958`
messages in the bin/findbutton skript every time i press the button before the actual mac-address is displayed (It does find the right mac address without problems though!).

My configuration:
Raspberry Pi Zero W running DietPi
Node.js v6.10.0
Node-Red v0.17.5
npm v5.5.1

Thanks in advance!

**Comment by nilsbernhar** [comment]
Hey,

I got it to work for me few weeks ago.
The problem was the "capabilities" of the program "node". As explained in [this link](https://www.blogging-it.com/node-pcap-module-error-socket-operation-not-permitted-fehler-wenn-pcapsession-geoeffnet-wird/programmierung/javascript/nodejs.html) (german, also mentioned in issue #2), this can be fixed using the `setcap` tool.

The exact code which fixed the problem for me was:
`sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))`

Hope this helps,
cheers!

**Comment by Noob-777** [comment]
> Hey,
> 
> I got it to work for me few weeks ago.
> The problem was the "capabilities" of the program "node". As explained in [this link](https://www.blogging-it.com/node-pcap-module-error-socket-operation-not-permitted-fehler-wenn-pcapsession-geoeffnet-wird/programmierung/javascript/nodejs.html) (german, also mentioned in issue #2), this can be fixed using the `setcap` tool.
> 
> The exact code which fixed the problem for me was:
> `sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))`
> 
> Hope this helps,
> cheers!

 thanks AlSa-Her! you have solved my node-red-contrib-amazondash problems!
